// Generated by pnpm module:sync from modules/installed.json. Do not edit by hand.
import type { ModuleDefinition } from '../packages/module-sdk/src/server.js';
import { definition as m0 } from '../modules/logging/definition.js';
if (m0.manifest.id !== 'logging') throw new Error('Module ID must match its installed package: logging');
import { definition as m1 } from '../modules/example/definition.js';
if (m1.manifest.id !== 'example') throw new Error('Module ID must match its installed package: example');
export const installedDefinitions = (production: boolean): ModuleDefinition[] => { void production; return [m0, ...(!production ? [m1] : [])]; };
