// Generated by pnpm module:sync from modules/installed.json. Do not edit by hand.
import type { ModuleDefinition } from '../packages/module-sdk/src/server.js';
import type { ProtectedModuleApi } from '../apps/web/src/protected-api.js';
import { definition as d0 } from '../modules/logging/definition.js';
import { registerApi as r0 } from '../modules/logging/api.js';
if (d0.manifest.id !== 'logging') throw new Error('Module ID must match its installed package: logging');
const m0 = { ...d0, register: r0 };
import { definition as d1 } from '../modules/example/definition.js';
import { registerApi as r1 } from '../modules/example/api.js';
if (d1.manifest.id !== 'example') throw new Error('Module ID must match its installed package: example');
const m1 = { ...d1, register: r1 };
export const installedApis = (production: boolean): Array<ModuleDefinition & {register(api: ProtectedModuleApi): void}> => { void production; return [m0, ...(!production ? [m1] : [])]; };
