// Generated by pnpm module:sync from modules/installed.json. Do not edit by hand.
import type { WebModule } from '../packages/module-sdk/src/browser.js';
import { definition as d0 } from '../modules/logging/definition.js';
const m0: WebModule = { id: d0.manifest.id, navigation: {label: d0.manifest.name, path:'/modules/logging', order:0}, load: () => import('../modules/logging/web.js') };
import { definition as d1 } from '../modules/example/definition.js';
const m1: WebModule = { id: d1.manifest.id, navigation: {label: d1.manifest.name, path:'/modules/example', order:1}, load: () => import('../modules/example/web.js') };
const production = import.meta.env.PROD && import.meta.env.MODE !== 'fixture';
void production;
export const webRegistry: WebModule[] = [m0, ...(!production ? [m1] : [])];
