import { test, expect } from '@playwright/test';
test('staff can inspect fixtures, save routing, preview and run a delivery test', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/auth/demo');
  await expect(page.getByRole('heading', { name: 'Your community, at a glance.' })).toBeVisible();
  await expect(page.getByText('LOCAL DEMO', { exact: false })).toBeVisible();
  await expect(page.getByText('Simulated', { exact: true })).toBeVisible();
  await expect(page.getByText('PocketBase', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= (visualViewport?.width ?? innerWidth) + 1)).toBe(true);
  await page.screenshot({ path: `test-results/overview-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: 'Configure logging' }).click();
  await page.getByLabel('Log destination').selectOption('100000000000000010');
  await page.getByRole('button', { name: 'Save settings' }).click();
  await expect(page.getByText('Saved.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Preview log' }).click();
  await expect(page.getByText('PREVIEW · NOT SENT', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Log destination')).toHaveValue('100000000000000010');
  await page.getByRole('link', { name: 'Diagnostics', exact: true }).click();
  await page.getByRole('button', { name: 'Send test log' }).click();
  await expect(page.getByText('Job completed:', { exact: false })).toBeVisible({ timeout: 15000 });
  await page.getByRole('link', { name: 'Events', exact: true }).click();
  await page.getByLabel('Event type').selectOption('logging.test');
  await expect(page.getByRole('link', { name: /Delivery test/ }).first()).toBeVisible();
  await page.getByRole('link', { name: /Delivery test/ }).first().click();
  await expect(page.getByText('Unknown. No confirmed audit evidence.', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
test('anonymous users see sign-in and protected APIs reject access', async ({ page, request }) => {
  await page.goto('/modules/logging');
  await expect(page.getByRole('link', { name: 'Continue with Discord' })).toBeVisible();
  const response = await request.get('/api/modules/logging/events');
  expect(response.status()).toBe(401);
});
test('a separate module saves settings, runs a job, and reads its own persisted data', async ({ page }) => {
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/auth/demo');
  await page.getByRole('link',{name:/^Modules/}).click();
  const card=page.locator('article').filter({has:page.getByRole('heading',{name:'Example module',exact:true})});
  await expect(card).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= (visualViewport?.width ?? innerWidth) + 1)).toBe(true);
  if (await card.getByRole('button',{name:'Enable',exact:true}).count()) await card.getByRole('button',{name:'Enable',exact:true}).click();
  await expect(card.getByText('Active',{exact:true})).toBeVisible({timeout:15000});
  await card.getByRole('link',{name:'Open module'}).click();
  const greeting=`Hello ${test.info().project.name} ${Date.now()}`;
  await page.getByLabel('Greeting',{exact:true}).fill(greeting);
  await expect(page.getByLabel('Greeting',{exact:true})).toHaveValue(greeting);
  // A polling refresh must not overwrite an unsaved draft.
  await page.waitForResponse(response=>response.url().endsWith('/api/modules/example/settings') && response.request().method()==='GET');
  await expect(page.getByLabel('Greeting',{exact:true})).toHaveValue(greeting);
  await page.getByRole('button',{name:'Save greeting',exact:true}).click();
  await expect(page.getByRole('button',{name:'Remember greeting',exact:true})).toBeEnabled({timeout:15000});
  await page.getByRole('button',{name:'Remember greeting',exact:true}).click();
  await expect(page.getByText('Task completed. Your greeting is remembered.',{exact:true})).toBeVisible({timeout:15000});
  await expect(page.locator('.embed-preview').getByText(greeting,{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Greeting',{exact:true})).toHaveValue(greeting);
  await expect(page.locator('.embed-preview').getByText(greeting,{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= (visualViewport?.width ?? innerWidth) + 1)).toBe(true);
  await page.screenshot({path:`test-results/module-${test.info().project.name}.png`,fullPage:true});
  await page.getByRole('link',{name:/^Modules/}).click();
  await card.getByRole('button',{name:'Disable',exact:true}).click();
  await expect(card.getByText('Disabled',{exact:true})).toBeVisible({timeout:15000});
  await card.getByRole('link',{name:'Open module'}).click();
  await expect(page.getByRole('button',{name:'Remember greeting',exact:true})).toBeDisabled();
  expect(errors).toEqual([]);
});
