import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test.use({ baseURL: 'http://localhost:3200' });
test('owner can provision local storage through the setup wizard', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  expect((await request.get('/setup-api/state')).status()).toBe(401);
  await page.goto('/setup');
  await expect(page.getByRole('heading', { name: 'Let’s get you connected.' })).toBeVisible();
  await page.getByLabel('Installation access key').fill('incorrect');
  await page.getByRole('button', { name: 'Unlock setup' }).click();
  await expect(page.getByText('Enter the installation access key from the bot host.')).toBeVisible();
  const accessKey = (await readFile('.local/e2e-installation/access.key', 'utf8')).trim();
  await page.getByLabel('Installation access key').fill(accessKey);
  await page.getByRole('button', { name: 'Unlock setup' }).click();
  await expect(page.getByRole('heading', { name: 'Where will your bot keep its data?' })).toBeVisible();
  await page.getByRole('button', { name: 'PostgreSQL Connect a database' }).click();
  await expect(page.getByLabel('Database host / IP')).toBeVisible();
  await page.getByRole('button', { name: 'Your PocketBase PocketHost or self-hosted' }).click();
  await expect(page.getByLabel('SFTP host', { exact: true })).toHaveValue('ftp.pockethost.io');
  await expect(page.getByRole('button', { name: 'Prepare storage' })).toBeDisabled();
  await page.getByRole('button', { name: 'On this host Managed PocketBase' }).click();
  await page.getByLabel('Community name').fill(`Setup ${test.info().project.name}`);
  await page.getByLabel('Discord server ID', { exact: true }).fill('100000000000000001');
  const prepared = page.waitForResponse(response => response.url().endsWith('/setup-api/prepare') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Prepare storage' }).click();
  const { id: jobId } = await (await prepared).json();
  let profileId = '';
  await expect.poll(async () => {
    const response = await request.get('/setup-api/state', { headers: { 'x-setup-key': accessKey } });
    const current = await response.json();
    if (current.job?.id === jobId && current.job.state === 'succeeded') profileId = current.job.profileId;
    return profileId;
  }, { timeout: 30000 }).not.toBe('');
  await expect(page.getByLabel('Storage profile')).toHaveValue(profileId);
  await expect(page.getByText('Storage is ready. Configuration saved securely.')).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('button', { name: 'Prepare storage' })).toBeEnabled();
  await expect(page.getByLabel('Discord application ID')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Activate this connection' })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= (visualViewport?.width ?? innerWidth) + 1)).toBe(true);
  await page.screenshot({ path: `test-results/setup-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Lock installation console' }).click();
  await expect(page.getByRole('button', { name: 'Unlock setup' })).toBeVisible();
  expect(errors).toEqual([]);
});
