import React, { lazy, Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Routes, Route, Link, Navigate } from 'react-router-dom';
import { QueryClient, QueryClientProvider, useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Activity, ArrowUpRight, Box, ChevronRight, CircleHelp, LayoutDashboard, LogOut, Settings, ShieldCheck, Radio, ArrowRight, SlidersHorizontal } from 'lucide-react';
import { Badge, Empty, Notice, SectionTitle } from '../../../packages/ui/src/index.js';
import type { ModuleInventory, UserSession } from '../../../packages/module-sdk/src/browser.js';
import type { LogEvent } from '../../../modules/logging/shared/settings.js';
import { webRegistry } from '../../../registry/web.js';
import { api, ApiError, SessionContext, useSession, setCsrf, type Status } from './api.js';
import { EventList } from '../../../modules/logging/web/EventList.js';
import { Brand, BotWorld } from './Brand.js';
import './style.css';
const SetupPage = lazy(() => import('./SetupPage.js'));

const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: 2000 } } });
const pages = webRegistry.map(module => ({ ...module, Component: lazy(module.load) }));
function App() {
  if (location.pathname === '/setup') return <Suspense fallback={<p>Opening setup…</p>}><SetupPage/></Suspense>;
  return <AuthenticatedApp/>;
}
function AuthenticatedApp() {
  const me = useQuery({ queryKey: ['me'], queryFn: () => api<UserSession>('/api/me'), refetchInterval: 60000 });
  if (me.isPending) return <main className="login"><Brand/><p>Opening your server console…</p></main>;
  if (!me.data) return <main className="login"><div className="login-card"><Brand/><span className="eyebrow">YOUR COMMUNITY STARTS HERE</span><h1>A happy little home<br/>for your community.</h1><p>Your private home for server activity, connected modules, and the details that matter.</p><a className="button primary" href="/auth/discord">Continue with Discord <ArrowUpRight size={17}/></a><small>Access is limited to your server’s approved staff.</small>{me.error && !(me.error instanceof ApiError && me.error.status === 401) && <Notice error>{me.error.message}</Notice>}</div><a className="login-note" href="https://www.omoworlds.com/">Made with imagination by OMOWorlds</a></main>;
  setCsrf(me.data.csrf);
  return <SessionContext.Provider value={me.data}><Shell /></SessionContext.Provider>;
}
function Shell() {
  const user = useSession(), cache = useQueryClient();
  const modules = useQuery({ queryKey: ['modules'], queryFn: () => api<ModuleInventory[]>('/api/modules'), refetchInterval: 5000 });
  const logout = useMutation({ mutationFn: () => api('/auth/logout', 'POST', {}), onSuccess: () => { cache.clear(); location.assign('/'); } });
  return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar">
    <Link className="brand" to="/"><Brand/></Link>
    <div className="community"><div className="community-icon">{user.communityName.slice(0, 2).toUpperCase()}</div><div><strong>{user.communityName}</strong><span>Private workspace</span></div><ShieldCheck size={16}/></div>
    <nav aria-label="Main navigation"><span className="nav-label">WORKSPACE</span><NavLink to="/" end><LayoutDashboard size={18}/>Overview</NavLink><NavLink to="/modules" end><Box size={18}/>Modules<span className="nav-count">{modules.data?.length ?? '—'}</span></NavLink><span className="nav-label modules-label">YOUR MODULES</span>{pages.filter(module => modules.data?.some(m => m.moduleId === module.id)).map(module => <NavLink key={module.id} to={module.navigation.path}><Activity size={18}/>{module.navigation.label}</NavLink>)}<span className="nav-label modules-label">MANAGEMENT</span><NavLink to="/settings"><Settings size={18}/>Settings</NavLink></nav>
    <div className="sidebar-bottom"><div className="scope-note"><ShieldCheck size={18}/><p>Your own little world.<br/><strong>We’ll help you care for it.</strong></p></div><div className="profile"><span className="avatar">{user.label.slice(0, 1)}</span><div><strong>{user.label}</strong><span>{user.access}</span></div><button className="icon-button" aria-label="Sign out" onClick={() => logout.mutate()} disabled={logout.isPending}><LogOut size={16}/></button></div>{logout.error && <Notice error>{logout.error.message}</Notice>}</div>
  </aside><div className="workspace"><div className="topbar"><span>{user.communityName}<ChevronRight size={13}/><strong>Server console</strong></span><span><span className="private-dot"/>Private deployment<CircleHelp size={17}/></span></div>{user.demo && <div className="demo-banner">LOCAL DEMO <span>Fixture activity · no Discord connection · changes stay in the demo database</span></div>}
    <main id="main">{modules.error && <Notice error>{modules.error.message}</Notice>}<Suspense fallback={<p className="loading">Loading module…</p>}><Routes><Route path="/" element={<Overview/>}/><Route path="/modules" element={<Modules/>}/><Route path="/settings" element={<SettingsPage/>}/>{pages.map(({ id, navigation, Component }) => <Route key={id} path={`${navigation.path}/*`} element={modules.data?.some(m => m.moduleId === id) ? <Component/> : modules.isPending ? <p>Loading modules…</p> : <Empty title="Module unavailable">This module is not installed for your workspace.</Empty>}/>) }<Route path="*" element={<Navigate to="/" replace/>}/></Routes></Suspense></main><footer>{user.botName}<a href="https://www.omoworlds.com/">Made with imagination by OMOWorlds</a><span>v0.1 · Channel logging preview</span></footer></div></div>;
}
function Overview() {
  const user = useSession();
  const status = useQuery({ queryKey: ['status'], queryFn: () => api<Status>('/api/status'), refetchInterval: 5000 });
  const modules = useQuery({ queryKey: ['modules'], queryFn: () => api<ModuleInventory[]>('/api/modules') });
  const hasLogging = modules.data?.some(m => m.moduleId === 'logging') ?? false;
  const events = useQuery({ queryKey: ['recent-events'], queryFn: () => api<{ events: LogEvent[] }>('/api/modules/logging/events?limit=5'), refetchInterval: 10000, enabled: hasLogging });
  const pending = status.data?.queue.filter(row => ['pending', 'sending'].includes(row.state)).reduce((sum, row) => sum + row.count, 0) ?? 0;
  const blocked = status.data?.queue.filter(row => ['failed', 'blocked'].includes(row.state)).reduce((sum, row) => sum + row.count, 0) ?? 0;
  return <><SectionTitle eyebrow="WORKSPACE / OVERVIEW" title="Your community, at a glance." description={`A little home for everything happening in ${user.communityName}.`} action={hasLogging && <Link className="button secondary" to="/modules/logging/routing"><SlidersHorizontal size={15}/>Configure logging</Link>}/>
    {status.error && <Notice error>{status.error.message}</Notice>}
    <section className="hero-panel"><div className="hero-copy"><div className="hero-kicker"><Radio size={15}/> SMALL BOT. BIG COMMUNITY ENERGY.</div><h2>Your world.<br/><span>A little more connected.</span></h2><p>More time for the people. Less time chasing the details.<br/>{' '}Let’s make your corner of Discord feel like home.</p><Link to={hasLogging ? "/modules/logging" : "/modules"}>{hasLogging ? "Explore activity" : "Explore modules"} <ArrowRight size={16}/></Link></div><BotWorld/></section>
    <div className="metric-grid"><Metric label="Gateway" value={status.isPending ? '…' : user.demo ? 'Simulated' : status.data?.online ? 'Connected' : 'Offline'} note={user.demo ? 'Local fixture worker' : status.data?.health ? `Heartbeat ${new Date(status.data.health.heartbeat).toLocaleTimeString()}` : 'Waiting for the first heartbeat'} icon={<Radio size={18}/>}/><Metric label="Retained events" value={status.data?.eventCount.toLocaleString() ?? '—'} note="Within your retention window" icon={<Activity size={18}/>}/><Metric label="Delivery queue" value={String(pending)} note={blocked ? `${blocked} need attention` : 'Pending and in-flight deliveries'} icon={<ArrowUpRight size={18}/>}/><Metric label="Active modules" value={`${modules.data?.filter(m => m.appliedEnabled).length ?? 0} / ${modules.data?.length ?? 0}`} note="Acknowledged by the worker" icon={<Box size={18}/>}/></div>
    <div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">THE LATEST</span><h2>Recent activity</h2></div>{hasLogging && <Link className="text-link" to="/modules/logging">View all <ArrowUpRight size={15}/></Link>}</div>{!hasLogging ? <Empty title="Your community’s next chapter">Install activity logging to see recent server changes here.</Empty> : events.error ? <Notice error>{events.error.message}</Notice> : events.isPending ? <p className="loading">Loading activity…</p> : <EventList events={events.data?.events ?? []}/>}</section><section className="panel health-panel"><div className="panel-heading"><div><span className="eyebrow">CONNECTED & CLEAR</span><h2>Workspace health</h2></div><ShieldCheck size={20}/></div><div className="health-row"><span>Dashboard access</span><Badge tone="good">Protected</Badge></div><div className="health-row"><span>Channel collection</span><Badge tone={modules.data?.find(m => m.moduleId === 'logging')?.appliedEnabled ? 'good' : 'warn'}>{modules.data?.find(m => m.moduleId === 'logging')?.appliedEnabled ? 'Enabled' : 'Not enabled'}</Badge></div><div className="health-row"><span>Storage</span><Badge>{status.data?.storageProvider === 'pocketbase' ? 'PocketBase' : status.data?.storageProvider === 'postgres' ? 'PostgreSQL' : 'Unknown'}</Badge></div><div className="health-row"><span>Delivery issues</span><Badge tone={blocked ? 'warn' : 'neutral'}>{blocked || 'None recorded'}</Badge></div><div className="capability-note"><span className="tiny-label">CURRENT COVERAGE</span><p>{hasLogging ? "Channel creation, edits, and deletion." : "Activity logging is not installed."}</p><small>Messages, members, roles, voice, and moderation are still on the build roadmap.</small></div>{hasLogging && <Link className="text-link" to="/modules/logging/diagnostics">Open diagnostics <ArrowRight size={15}/></Link>}</section></div>
  </>;
}
function Metric({ label, value, note, icon }: { label: string; value: string; note: string; icon: React.ReactNode }) { return <div className="metric"><div><span>{label}</span>{icon}</div><strong>{value}</strong><small>{note}</small></div>; }
function Modules() {
  const user = useSession(), cache = useQueryClient();
  const modules = useQuery({ queryKey: ['modules'], queryFn: () => api<ModuleInventory[]>('/api/modules'), refetchInterval: 2000 });
  const change = useMutation({ mutationFn: (module: ModuleInventory) => api(`/api/modules/${module.moduleId}/state`, 'PATCH', { revision: module.desiredRevision, enabled: !module.enabled }), onSuccess: () => cache.invalidateQueries({ queryKey: ['modules'] }) });
  return <><SectionTitle eyebrow="WORKSPACE / MODULES" title="Make room for more." description="Independent tools, one connected workspace. Enable only what your community needs."/>{change.error && <Notice error>{change.error.message}</Notice>}{modules.error && <Notice error>{modules.error.message}</Notice>}<div className="module-grid">{modules.data?.map(module => <article className="panel module-card" key={module.moduleId}><div className="module-card-top"><span className="module-icon"><Activity size={24}/></span><Badge tone={module.applyError ? 'bad' : module.desiredRevision !== module.appliedRevision ? 'warn' : module.appliedEnabled ? 'good' : 'neutral'}>{module.applyError ? 'Apply failed' : module.desiredRevision !== module.appliedRevision ? 'Pending' : module.appliedEnabled ? 'Active' : 'Disabled'}</Badge></div><h2>{module.manifest.name}</h2><p>{module.manifest.description}</p><p className="module-requirements">{module.manifest.dependencies.length ? `Requires: ${module.manifest.dependencies.join(', ')}. ` : ''}{module.manifest.requiredIntents.length ? `Discord events: ${module.manifest.requiredIntents.join(', ')}.` : 'No extra Discord events required.'}</p><span className="tiny-label">VERSION {module.manifest.version} · REVISION {module.appliedRevision}/{module.desiredRevision}</span>{module.applyError && <Notice error>{module.applyError}</Notice>}<div className="module-actions">{webRegistry.some(entry => entry.id === module.moduleId) ? <Link className="button secondary" to={`/modules/${module.moduleId}`}>Open module <ArrowUpRight size={15}/></Link> : <small>No dashboard page installed.</small>}<button disabled={user.access === 'viewer' || change.isPending} onClick={() => change.mutate(module)}>{module.enabled ? 'Disable' : 'Enable'}</button></div><small>Disabling waits for the worker. A send already in flight may finish.</small></article>)}</div></>;
}
function SettingsPage() {
  const user = useSession();
  return <><SectionTitle eyebrow="MANAGEMENT / SETTINGS" title="Your workspace essentials." description="Deployment identity and access, kept in one place."/><section className="panel settings-summary">{user.access === 'owner' && <a className="button secondary" href="/setup">Manage installation & storage <ArrowUpRight size={15}/></a>}<h2>Community</h2><dl><dt>Display name</dt><dd>{user.communityName}</dd><dt>Bot name</dt><dd>{user.botName}</dd><dt>Configured server ID</dt><dd className="mono">{user.guildId}</dd><dt>Your access</dt><dd>{user.access}</dd><dt>Deployment mode</dt><dd>{user.demo ? 'Local fixture demo' : 'Private single-server deployment'}</dd></dl><Notice>Display names and staff access lists are configured by the deployment owner. Your Discord membership is rechecked before every change.</Notice><p>Stored event metadata expires automatically. Messages already delivered to Discord follow the log channel’s own retention policy.</p></section></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></React.StrictMode>);
