import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, Check, Cloud, Database, HardDrive, KeyRound, LoaderCircle, Radio, Server, ShieldCheck } from 'lucide-react';
import type { publicProfile, SetupJob } from '../../setup/src/model.js';
import { Notice } from '../../../packages/ui/src/index.js';
import { Brand, BotWorld } from './Brand.js';
import './setup.css';
type Profile = ReturnType<typeof publicProfile>;
type State = { profiles: Profile[]; activeId: string | null; runtime: string; job: SetupJob | null };
const initial = { name: 'My Community', guildId: '', url: '', email: '', password: '', sftpHost: 'ftp.pockethost.io', sftpPort: '2222', sftpUsername: '', directory: '', privateKey: '', passphrase: '', pgHost: '', pgPort: '5432', database: '', username: '', pgPassword: '' };
export default function SetupPage() {
  const key = useRef(''), [enteredKey, setEnteredKey] = useState(''), [unlocked, setUnlocked] = useState(false), [available, setAvailable] = useState<boolean | null>(null);
  const [state, setState] = useState<State>(), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [kind, setKind] = useState<'local' | 'remote' | 'postgres'>('local'), [form, setForm] = useState(initial), [tls, setTls] = useState(true), [fingerprint, setFingerprint] = useState(''), [trusted, setTrusted] = useState(false);
  const [selected, setSelected] = useState(''), [useTargetData, setUseTargetData] = useState(false);
  const [discord, setDiscord] = useState({ applicationId: '', botToken: '', clientSecret: '', ownerId: '', botName: 'OMO Bot' });
  const lastCompleted = useRef('');
  async function call<T>(path: string, body?: unknown): Promise<T> {
    const response = await fetch(`/setup-api/${path}`, { method: body === undefined ? 'GET' : 'POST', headers: { 'x-setup-key': key.current, ...(body === undefined ? {} : { 'content-type': 'application/json' }) }, body: body === undefined ? undefined : JSON.stringify(body) });
    const data = await response.json(); if (!response.ok) throw new Error(typeof data.error === 'string' ? data.error : 'Setup is unavailable.'); return data;
  }
  useEffect(() => { void fetch('/setup-api/info').then(r => r.ok ? r.json() : { available: false }).then(d => setAvailable(d.available === true)).catch(() => setAvailable(false)); }, []);
  useEffect(() => {
    if (!unlocked) return;
    let stopped = false;
    const refresh = async () => { try { const value = await call<State>('state'); if (!stopped) { setState(value); if (value.job?.state === 'succeeded' && value.job.id !== lastCompleted.current) { lastCompleted.current = value.job.id; if (value.job.profileId) setSelected(value.job.profileId); setForm(f => ({ ...f, password: '', pgPassword: '', privateKey: '', passphrase: '' })); setDiscord(d => ({ ...d, botToken: '', clientSecret: '' })); } } } catch (e) { if (!stopped) setError((e as Error).message); } };
    void refresh(); const timer = setInterval(() => { void refresh(); }, 1000); return () => { stopped = true; clearInterval(timer); };
  }, [unlocked]);
  async function action(work: () => Promise<unknown>) { setBusy(true); setError(''); try { await work(); setState(await call<State>('state')); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const running = busy || state?.job?.state === 'running';
  const change = (name: keyof typeof initial, value: string) => { setForm(f => ({ ...f, [name]: value })); if (name === 'sftpHost' || name === 'sftpPort') { setFingerprint(''); setTrusted(false); } };
  function field(name: keyof typeof initial, label: string, type = 'text', placeholder = '', required = true) { return <label>{label}<input type={type} value={form[name]} onChange={e => change(name, e.target.value)} placeholder={placeholder} required={required} autoComplete={type === 'password' ? 'new-password' : 'off'} maxLength={type === 'password' ? 8192 : 256}/></label>; }
  async function prepare(event: FormEvent) {
    event.preventDefault();
    const storage = kind === 'local' ? { kind } : kind === 'remote' ? { kind, url: form.url, email: form.email, password: form.password, sftp: { host: form.sftpHost, port: Number(form.sftpPort), username: form.sftpUsername, directory: form.directory, privateKey: form.privateKey, passphrase: form.passphrase, fingerprint } } : { kind, host: form.pgHost, port: Number(form.pgPort), database: form.database, username: form.username, password: form.pgPassword, tls };
    await action(() => call('prepare', { name: form.name, guildId: form.guildId, storage }));
  }
  const profile = state?.profiles.find(p => p.id === selected);
  return <div className="setup-shell"><header className="setup-header"><a className="brand" href="/"><Brand/></a><span><ShieldCheck size={16}/> Owner console</span></header><main className="setup-main">
    <div className="setup-intro"><span className="eyebrow">A HOME FOR YOUR COMMUNITY</span><h1>Make yourself<br/><em>at home.</em></h1><p>Your bot. Your server. Your choice of storage.<br/>We’ll take care of connecting the pieces.</p><BotWorld compact/><div className="setup-steps"><span><b>01</b> Choose storage</span><span><b>02</b> Connect Discord</span><span><b>03</b> Bring it online</span></div></div>
    {available === null ? <section className="panel"><p>Checking installation service…</p></section> : !available ? <section className="panel setup-unlock"><Server size={28}/><h2>Start the installation console.</h2><p>This dashboard is running without the managed launcher. On the bot host, run <code>pnpm build</code>, then <code>pnpm start</code>. The terminal shows your setup address and owner access key.</p><p>The fixture demo cannot provision or change your live bot.</p><a className="text-link" href="/">Return to dashboard <ArrowRight size={16}/></a></section> : !unlocked ? <form className="panel setup-unlock" onSubmit={e => { e.preventDefault(); void action(async () => { key.current = enteredKey; await call('state'); setEnteredKey(''); setUnlocked(true); }); }}><KeyRound size={28}/><span className="eyebrow">YOUR INSTALLATION, PROTECTED</span><h2>Let’s get you connected.</h2><p>Enter the owner access key shown when you started this bot host. Setup works before a database or Discord login exists.</p><label>Installation access key<input type="password" value={enteredKey} onChange={e => setEnteredKey(e.target.value)} required autoComplete="off"/></label><button className="primary" disabled={busy}>Unlock setup <ArrowRight size={16}/></button>{error && <Notice error>{error}</Notice>}</form> : <div className="setup-workspace">
      {error && <Notice error>{error}</Notice>}
      <form className="panel setup-form" onSubmit={e => { void prepare(e); }}><div className="setup-section-title"><span className="step-number">01</span><div><h2>Where will your bot keep its data?</h2><p>Choose a home. We’ll prepare the database for you.</p></div></div><fieldset disabled={running}><div className="setup-fields">{field('name', 'Community name')}{field('guildId', 'Discord server ID', 'text', '17–20 digit server ID')}</div>
        <div className="provider-options" role="group" aria-label="Storage provider">{([{ id: 'local', title: 'On this host', subtitle: 'Managed PocketBase', Icon: HardDrive }, { id: 'remote', title: 'Your PocketBase', subtitle: 'PocketHost or self-hosted', Icon: Cloud }, { id: 'postgres', title: 'PostgreSQL', subtitle: 'Connect a database', Icon: Database }] as const).map(({ id, title, subtitle, Icon }) => <button key={id} type="button" className={`provider-option ${kind === id ? 'selected' : ''}`} aria-pressed={kind === id} onClick={() => setKind(id)}><Icon size={23}/><strong>{title}</strong><small>{subtitle}</small>{kind === id && <Check className="provider-check" size={15}/>}</button>)}</div>
        {kind === 'local' ? <div className="setup-context"><HardDrive size={22}/><div><strong>Everything together, ready to go.</strong><p>We’ll install PocketBase on the machine running this bot, create its database, and apply migrations. Data persists across restarts. No database account needed.</p></div></div> : kind === 'remote' ? <><div className="setup-fields">{field('url', 'PocketBase URL', 'url', 'https://your-instance.pockethost.io')}{field('email', 'PocketBase superadmin email', 'email')}{field('password', 'PocketBase superadmin password', 'password')}</div><div className="setup-divider"><h3>Automatic file deployment</h3><p>Your superadmin login connects the database. SFTP access lets us install its hooks and migrations. These deployment credentials are used for this setup only.</p></div><div className="setup-fields">{field('sftpHost', 'SFTP host')}{field('sftpPort', 'SFTP port', 'number')}{field('sftpUsername', 'SFTP username / PocketHost email')}{field('directory', 'Instance folder', 'text', 'your-instance')}
        <label className="full">SSH private key<textarea value={form.privateKey} onChange={e => change('privateKey', e.target.value)} required rows={4} spellCheck={false} placeholder="Paste your instance-scoped Ed25519 private key"/></label>{field('passphrase', 'Key passphrase (if encrypted)', 'password', '', false)}</div><button type="button" className="secondary" onClick={() => { void action(async () => { const result = await call<{ fingerprint: string }>('probe', { host: form.sftpHost, port: Number(form.sftpPort) }); setFingerprint(result.fingerprint); setTrusted(false); }); }}>Check SFTP server</button>{fingerprint && <div className="fingerprint"><code>{fingerprint}</code><label className="checkbox-label"><input type="checkbox" checked={trusted} onChange={e => setTrusted(e.target.checked)}/>I recognize this server fingerprint and trust this connection.</label></div>}<small>PocketHost uses port 2222 and a registered Ed25519 key. Files upload automatically. Hosts that disable hook reload may require a restart from their console.</small></> : <><div className="setup-fields">{field('pgHost', 'Database host / IP', 'text', 'db.example.com')}{field('pgPort', 'Database port', 'number')}{field('database', 'Database name')}{field('username', 'Database username')}{field('pgPassword', 'Database password', 'password')}</div><label className="checkbox-label"><input type="checkbox" checked={tls} onChange={e => setTls(e.target.checked)}/>Use TLS and verify the server certificate</label><small>Connect an existing database. The supplied role needs permission to run migrations and access the bot’s tables. Local private deployments can disable TLS.</small></>}
        <div className="setup-form-footer"><small>Creates tables and verifies access.<br/>Existing data is never copied between providers.</small><button className="primary" disabled={running || (kind === 'remote' && (!trusted || !fingerprint))}>{running ? <LoaderCircle size={16} className="spin"/> : <ArrowRight size={16}/>}Prepare storage</button></div></fieldset></form>
      {state?.job && <section className="panel setup-progress" aria-live="polite"><div className="panel-heading"><h2>{state.job.state === 'running' ? 'Connecting the pieces…' : state.job.state === 'failed' ? 'This step needs attention.' : 'All set for the next step.'}</h2>{state.job.state === 'running' ? <LoaderCircle className="spin" size={20}/> : state.job.state === 'succeeded' ? <Check size={20}/> : null}</div><ol>{state.job.steps.map((step, index) => <li key={index}>{step}</li>)}</ol>{state.job.error && <Notice error>{state.job.error}</Notice>}</section>}
      {!!state?.profiles.length && <section className="panel setup-form"><div className="setup-section-title"><span className="step-number">02</span><div><h2>Your connections</h2><p>Choose a prepared profile, then connect Discord.</p></div></div><label>Storage profile<select value={selected} onChange={e => { setSelected(e.target.value); setUseTargetData(false); }}><option value="">Choose a profile</option>{state.profiles.map(p => <option key={p.id} value={p.id}>{p.name} · {p.kind === 'postgres' ? 'PostgreSQL' : 'PocketBase'} · {p.ready ? 'Ready' : 'Setup incomplete'}</option>)}</select></label>{profile && <><p className="setup-endpoint">{profile.endpoint} · Server {profile.guildId}</p>{!profile.ready ? <Notice error>Setup is incomplete. Retry preparation with the same instance details.</Notice> : <><form onSubmit={e => { e.preventDefault(); void action(() => call('discord', { profileId: selected, discord })); }}><fieldset disabled={running}><div className="setup-fields">{([{ id: 'applicationId', label: 'Discord application ID' }, { id: 'ownerId', label: 'Your Discord user ID' }, { id: 'botName', label: 'Bot display name' }, { id: 'botToken', label: 'Discord bot token' }, { id: 'clientSecret', label: 'Discord OAuth client secret' }] as const).map(({ id, label }) => <label key={id}>{label}<input required type={id === 'botToken' || id === 'clientSecret' ? 'password' : 'text'} autoComplete="off" value={discord[id]} onChange={e => setDiscord(d => ({ ...d, [id]: e.target.value }))}/></label>)}</div><p>Register this OAuth callback in your Discord application:</p><code className="setup-callback">{location.origin}/auth/discord/callback</code><button className="secondary">{profile.hasDiscord ? 'Replace Discord credentials' : 'Save Discord connection'}</button></fieldset></form><div className="setup-divider"><div className="setup-section-title"><span className="step-number">03</span><div><h2>Bring your bot online.</h2><p>Current service status: <strong>{state.runtime}</strong></p></div></div><label className="checkbox-label"><input type="checkbox" checked={useTargetData} onChange={e => setUseTargetData(e.target.checked)}/>Use this database’s data. Any previous database keeps its own settings and history.</label><div className="setup-activate"><button className="primary" disabled={running || !profile.hasDiscord || !useTargetData} onClick={() => { void action(() => call('activate', { profileId: selected, useTargetData: true })); }}><Radio size={17}/>Activate this connection</button>{state.runtime === 'running' && <><a className="button secondary" href="/">Open dashboard <ArrowRight size={15}/></a><button disabled={running} onClick={() => { void action(() => call('stop', {})); }}>Stop services</button></>}</div></div></> }</>}</section>}
      <button className="text-link" onClick={() => { key.current = ''; setUnlocked(false); setState(undefined); setForm(initial); setDiscord({ applicationId: '', botToken: '', clientSecret: '', ownerId: '', botName: 'OMO Bot' }); }}>Lock installation console <KeyRound size={14}/></button>
    </div>}
  </main><footer className="setup-bottom"><a href="https://www.omoworlds.com/">OMOBot · Made with imagination by OMOWorlds</a><span>Storage stays yours.</span></footer></div>;
}
