import { execFileSync } from 'node:child_process';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

type Dependency = { name: string; versions: string[]; paths: string[]; license: string; homepage?: string };
const report = JSON.parse(execFileSync('pnpm', ['licenses', 'list', '--prod', '--json'], { encoding: 'utf8' })) as Record<string, Dependency[]>;
const supplements: Record<string, string> = {
  'drizzle-orm': 'drizzle-orm', '@sapphire/async-queue': 'sapphire-utilities',
  '@sapphire/snowflake': 'sapphire-utilities', 'abstract-logging': 'abstract-logging',
};
const lines = ['# Third-party notices', '', 'Generated by `pnpm licenses:generate` from the installed production dependency graph. These components retain their own licenses; OMOBot’s Apache 2.0 license does not replace them. Original attribution text is preserved, including authors’ published contact details.', '', 'The dashboard bundles DM Sans and Manrope (SIL Open Font License 1.1), Lucide/Feather icons and JavaScript libraries. Their notices appear below. PocketBase is downloaded separately from its official releases under its own MIT license: https://github.com/pocketbase/pocketbase/blob/master/LICENSE.md. PostgreSQL is separately installed software under the PostgreSQL License: https://www.postgresql.org/about/licence/.', ''];
for (const dep of Object.values(report).flat().sort((a, b) => a.name.localeCompare(b.name))) {
  lines.push(`## ${dep.name} (${dep.versions.join(', ')})`, '', `License: ${dep.license}`, '');
  if (dep.homepage) lines.push(`Project: ${dep.homepage}`, '');
  const notices = new Set<string>();
  for (const directory of dep.paths) {
    const files = await readdir(directory, { withFileTypes: true });
    for (const file of files.filter(f => f.isFile() && /^(licen[cs]e|copying|notice)([.-]|$)/i.test(f.name))) {
      notices.add((await readFile(join(directory, file.name), 'utf8')).trim());
    }
    if (!notices.size) {
      const readme = files.find(f => f.isFile() && /^readme\.md$/i.test(f.name));
      if (readme) {
        const text = await readFile(join(directory, readme.name), 'utf8');
        const section = text.match(/^## license\s*\n([\s\S]*)/im)?.[1];
        if (section?.includes('Permission is hereby granted')) notices.add(section.trim());
      }
    }
  }
  if (!notices.size && supplements[dep.name]) notices.add((await readFile(`licenses/supplemental/${supplements[dep.name]}.txt`, 'utf8')).trim());
  if (!notices.size) throw new Error(`Missing license text for ${dep.name}; review its upstream license before distributing.`);
  for (const notice of notices) lines.push('```text', notice, '```', '');
}
await writeFile('THIRD_PARTY_NOTICES.md', lines.join('\n'));
console.info('Updated third-party notices without local dependency paths.');
