import { readFile, writeFile, mkdir, access } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
const idSchema = z.string().regex(/^[a-z][a-z0-9-]{0,31}$/).refine(id => id !== 'bot', 'The bot name is reserved.');
const catalogSchema = z.array(z.object({ id: idSchema, developmentOnly: z.boolean() }).strict()).max(100);
export async function syncModules(root = process.cwd()) {
  const entries = catalogSchema.parse(JSON.parse(await readFile(resolve(root, 'modules/installed.json'), 'utf8')));
  if (new Set(entries.map(e => e.id)).size !== entries.length) throw new Error('Duplicate installed module ID.');
  for (const entry of entries) for (const file of ['definition.ts', 'bot.ts', 'api.ts', 'web.tsx']) await access(resolve(root, 'modules', entry.id, file));
  const header = '// Generated by pnpm module:sync from modules/installed.json. Do not edit by hand.\n';
  const select = (suffix: string) => entries.map((entry, i) => entry.developmentOnly ? `...(!production ? [m${i}${suffix}] : [])` : `m${i}${suffix}`).join(', ');
  const definitions = header + "import type { ModuleDefinition } from '../packages/module-sdk/src/server.js';\n" + entries.map((e,i) => `import { definition as m${i} } from '../modules/${e.id}/definition.js';\nif (m${i}.manifest.id !== '${e.id}') throw new Error('Module ID must match its installed package: ${e.id}');`).join('\n') + `\nexport const installedDefinitions = (production: boolean): ModuleDefinition[] => { void production; return [${select('')}]; };\n`;
  const factories = header + "import type { BotModule } from '../packages/module-sdk/src/server.js';\n" + "import type { ModulePackageServices } from '../packages/core/src/module-package.js';\n" + entries.map((e,i) => `import { createBot as m${i} } from '../modules/${e.id}/bot.js';`).join('\n') + `\nexport const installedBots = (services: ModulePackageServices, production: boolean): BotModule[] => { void services; void production; return [${select('(services)')}]; };\n`;
  const apis = header + "import type { ModuleDefinition } from '../packages/module-sdk/src/server.js';\nimport type { ProtectedModuleApi } from '../apps/web/src/protected-api.js';\n" + entries.map((e,i) => `import { definition as d${i} } from '../modules/${e.id}/definition.js';\nimport { registerApi as r${i} } from '../modules/${e.id}/api.js';\nif (d${i}.manifest.id !== '${e.id}') throw new Error('Module ID must match its installed package: ${e.id}');\nconst m${i} = { ...d${i}, register: r${i} };`).join('\n') + `\nexport const installedApis = (production: boolean): Array<ModuleDefinition & {register(api: ProtectedModuleApi): void}> => { void production; return [${select('')}]; };\n`;
  const web = header + "import type { WebModule } from '../packages/module-sdk/src/browser.js';\n" + entries.map((e,i) => `import { definition as d${i} } from '../modules/${e.id}/definition.js';\nconst m${i}: WebModule = { id: d${i}.manifest.id, navigation: {label: d${i}.manifest.name, path:'/modules/${e.id}', order:${i}}, load: () => import('../modules/${e.id}/web.js') };`).join('\n') + `\nconst production = import.meta.env.PROD && import.meta.env.MODE !== 'fixture';\nvoid production;\nexport const webRegistry: WebModule[] = [${select('')}];\n`;
  await mkdir(resolve(root,'registry'),{recursive:true});
  for (const [file, text] of Object.entries({ 'definitions.ts': definitions, 'installed-bots.ts': factories, 'installed-apis.ts': apis, 'web.ts': web })) {
    const path = resolve(root,'registry',file); let old = ''; try { old = await readFile(path,'utf8'); } catch { /* first generation */ }
    if (old !== text) await writeFile(path,text);
  }
}
export async function scaffoldModule(root: string, rawId: string, sourceRoot = process.cwd()) {
  const id = idSchema.parse(rawId), target = resolve(root,'modules',id);
  const catalogFile=resolve(root,'modules/installed.json'), entries=catalogSchema.parse(JSON.parse(await readFile(catalogFile,'utf8')));
  if (entries.some(e => e.id===id)) throw new Error('That module is already registered.');
  // Read/transform all inputs before creating a target; mkdir refuses existing directories.
  const files = await Promise.all(['definition.ts','bot.ts','api.ts','web.tsx'].map(async file => {
    let source = await readFile(resolve(sourceRoot,'modules/example',file),'utf8');
    source = source.replaceAll('exampleDefinition','moduleDefinition').replaceAll('exampleModule','moduleImplementation').replaceAll('ExamplePage','ModulePage');
    source = source.replaceAll('example',id).replaceAll('Example module', id.split('-').map(s=>s[0]!.toUpperCase()+s.slice(1)).join(' '));
    source = source.replaceAll('Development-only proof of the module contract.', 'A custom module for your community.').replaceAll('Development-only', 'Custom');
    return [file,source] as const;
  }));
  await mkdir(target); // Do not overwrite source, including an empty pre-existing directory.
  for (const [file,source] of files) await writeFile(resolve(target,file),source,{flag:'wx'});
  await writeFile(resolve(target,'README.md'),`# ${id}\n\nCustomize definition.ts, bot.ts, api.ts and web.tsx. See ../../docs/MODULES.md. This is trusted server code; rebuild and restart after installing.\n`);
  await writeFile(catalogFile,JSON.stringify([...entries,{id,developmentOnly:false}],null,2)+'\n');
  await syncModules(root);
}
export async function registerModule(root: string, rawId: string, remove = false) {
  const id=idSchema.parse(rawId),file=resolve(root,'modules/installed.json');
  const entries=catalogSchema.parse(JSON.parse(await readFile(file,'utf8')));
  if (!remove) {
    if (entries.some(e=>e.id===id)) throw new Error('That module is already registered.');
    for (const source of ['definition.ts','bot.ts','api.ts','web.tsx']) await access(resolve(root,'modules',id,source));
  } else if (!entries.some(e=>e.id===id)) throw new Error('That module is not installed.');
  await writeFile(file,JSON.stringify(remove ? entries.filter(e=>e.id!==id) : [...entries,{id,developmentOnly:false}],null,2)+'\n');
  await syncModules(root);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const command=process.argv[2];
  if (command === 'create') { if (!process.argv[3]) throw new Error('Usage: pnpm module:create module-name'); await scaffoldModule(process.cwd(),process.argv[3]); console.info(`Created modules/${process.argv[3]}. Customize it, then build and restart OMOBot.`); }
  else if (command === 'add' || command === 'remove') { if (!process.argv[3]) throw new Error('Supply a module name.'); await registerModule(process.cwd(), process.argv[3], command === 'remove'); console.info('Package selection updated. Rebuild and restart; stored module data is retained.'); }
  else if (command === 'sync') { await syncModules(); console.info('Module registries synchronized.'); }
  else throw new Error('Use module:create or module:sync.');
}
